# configmap.yaml
{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "ethereum.fullname" . }}
data:
  {{- range .Values.env }}
  {{ .name | lower }}: {{ .value | quote }}
  {{- end }}
{{- end }}