{{- if .Values.secrets }}
apiVersion: v1
kind: ConfigMap
kind: Secret
metadata:
  name:  {{ include "ethereum.fullname" . }}
data:
  {{- range .Values.secrets }}
  {{ .name | lower }}: {{ .value | b64enc | quote }}
  {{- end }}
{{- end }}