name: Destroy infrastructure

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CLOUD_KEYFILE_JSON }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Set Environment Variables
        run: |
          echo "export GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" > .env.in
          echo "export GCP_REGION=${{ vars.GCP_REGION }}" >> .env.in
          echo "export APP_DOMAIN=${{ vars.APP_DOMAIN }}" >> .env.in
          echo "export APP_VERSION=${{ vars.APP_VERSION }}" >> .env.in
          echo "export AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> .env.in
          echo "export AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env.in
          echo "export AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}" >> .env.in
          echo "export CICD=${{ vars.CICD }}" >> .env.in

      - name: Generate .env.out
        run: |
          chmod +x scripts/genenv.sh
          ./scripts/genenv.sh
      - name: Destroy
        run: |
          chmod +x scripts/destroy.sh
          source .env.out
          ./scripts/destroy.sh
